---
- name: 'Handlers Task | Enable teleport at boot'
  become: true
  become_user: 'root'
  ansible.builtin.systemd:
    name: teleport
    enabled: yes
    daemon_reload: yes

- name: 'Handlers Task | Restart teleport'
  become: true
  become_user: 'root'
  ansible.builtin.shell: "systemctl restart teleport.service"
  async: 1
  poll: 0
  register: teleport_restart

- name: 'Handlers Task | Wait for restart'
  ansible.builtin.wait_for_connection:
    delay: 10
    sleep: 5
    timeout: 300

- name: 'Handlers Task | Check restart status'
  ansible.builtin.async_status:
    jid: "{{ teleport_restart.ansible_job_id }}"
  ignore_errors: true
