---
- name: 'Import validator'
  tags:
    - always
  ansible.builtin.import_tasks: validator/main.yml

- name: 'Import RHEL tasks'
  when: ansible_os_family == 'RedHat'
  ansible.builtin.import_tasks: rhel/main.yml

- name: 'Import Debian tasks'
  when: ansible_os_family == 'Debian'
  ansible.builtin.import_tasks: debian/main.yml

- name: 'Import configure tasks'
  ansible.builtin.import_tasks: configure/main.yml
