---
- name: 'RHEL | Deploy teleport repository'
  ansible.builtin.template:
    src: etc/yum.repos.d/teleport.repo.j2
    dest: '/etc/yum.repos.d/teleport.repo'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  become: true
  when: "'teleport-cluster' not in group_names"
  tags:
    - install
    - update

- name: 'RHEL | Teleport install'  # noqa package-latest
  ansible.builtin.package:
    name: teleport
    state: latest
  become: true
  notify: "Restart teleport"
  tags:
    - install
    - update
