---
- name: 'Configure | Generate token to link host to cluster'
  tags:
    - install
    - enroll
  block:
    - name: 'Configure | Delete existing token to renew for current host'  # noqa command-instead-of-shell no-changed-when
      ansible.builtin.shell: "tctl tokens rm {{ join_token }}"
      when: join_token is defined
      delegate_to: "{{ groups['teleport-cluster'][0] }}"
      become: true

    - name: 'Configure | Generate a new node token'  # noqa command-instead-of-shell no-changed-when
      ansible.builtin.shell: "tctl tokens add --ttl={{ teleport_token_ttl }} --type=node --format=json"
      when: join_token is not defined
      register: join_token
      delegate_to: "{{ groups['teleport-cluster'][0] }}"
      become: true

    - name: 'Configure | Set facts with token'
      ansible.builtin.set_fact:
        token: "{{ join_token.stdout | from_json | json_query('token') }}"
      become: true

    - name: 'Configure | Deploy configuration to host'
      ansible.builtin.template:
        dest: '/etc/teleport.yaml'
        src: 'etc/teleport.yml.j2'
        owner: 'root'
        group: 'root'
        mode: '0640'
      become: true
      when:
        - "'teleport-cluster' not in group_names"
      notify: 'Restart teleport'

- name: 'Configure | Load and decode teleport configuration as yaml file'
  tags:
    - configure
  block:
    - name: 'Configure | Retreive existing configuration file content'
      ansible.builtin.slurp:
        src: '/etc/teleport.yaml'
      register: teleport_config_slurp
      become: true

    - name: 'Configure | Decode and store configuration as variable'
      ansible.builtin.set_fact:
        teleport_config_content: "{{ teleport_config_slurp.content | b64decode | from_yaml }}"

    - name: 'Configure | Set token with existing token'
      ansible.builtin.set_fact:
        token: "{{ teleport_config_content['teleport']['join_params']['token_name'] }}"
        teleport_cluster_capin: "{{ teleport_config_content['teleport']['ca_pin'] }}"
        teleport_cluster: "{{ teleport_config_content['teleport']['auth_servers'] }}"

    - name: 'Configure | Deploy configuration to host'
      ansible.builtin.template:
        dest: '/etc/teleport.yaml'
        src: 'etc/teleport.yml.j2'
        owner: 'root'
        group: 'root'
        mode: '0640'
      become: true
      notify: 'Restart teleport'
      when:
        - "'teleport-cluster' not in group_names"
